### PR TITLE
✨ Start of e2e push on main tests

### PR DESCRIPTION
**Pull request by laurentsimon**
This is an example of e2e test I'm starting to build.

Maybe these tests should live under a different repos containing all these end-to-end tests, as it will be in practice for users.

/cc @MarkLodato Wdut?

### CODE REVIEW

**Comment by joshuagl** [comment]
It would be good to have a slsa-github-generator-examples repo that acts as both e2e tests and sample code.

**Comment by laurentsimon** [comment]
Great. Let's create another repo. I'll merge this PR for now to build the foundation of these tests.
@MarkLodato do you want to crate the new repo?

**Comment by MarkLodato** [comment]
Done: https://github.com/slsa-framework/slsa-github-generator-examples

**Comment by MarkLodato** [comment]
Actually I renamed to https://github.com/slsa-framework/example-package since we can use this same package with multiple builders to show how to do the same thing multiple ways. I'll populate it with what I already have.

**Comment by laurentsimon** [comment]
Thanks. I've created our first e2e test that will run daily on the main branch. I will add more tests, including verification frm the slsa-verifier as we go along.

If the e2e fails, it will create an issue on this repo, like https://github.com/slsa-framework/slsa-github-generator-go/issues/76

Closing the PR.

**Pull request closed without merging**
