### PR TITLE
✨ Add e2e pre-submits

### PR DESCRIPTION
**Pull request by laurentsimon**
Add pre-submit for the re-usable workflow on incoming pull request

### CODE REVIEW

**Review by asraa — APPROVED** [review]
Thanks!

**Comment by laurentsimon** [comment]
@ianlewis I need some input.
This PR adds e2e pre-submit. But: pull request don't have access to the needed permissions `token-id: write` because permissions are set read by default.

What I initially set out to do was to still have this e2e test as pre-submit, but not sign the provenance, since this is the best that can be done. The problem is that we currently create the OIDCClient and expect it to use it https://github.com/slsa-framework/slsa-github-generator-go/blob/main/pkg/provenance.go#L107

I'm wondering how we could accommodate my use case of pull-requests:
1. Allow an empty OIDC client
2. Use an interface so that the reusable workflow can create its own OIDC client and pass it to the `HostedActionsProvenance()` call.
3. Any other ideas?

I think (1) is better: the worst that happens is a re-usable workflow not passing a client and getting not signature, which would be caught by the verifier anyway.

Wdut?

**Comment by ianlewis** [comment]
Right now we're just using the token to get the `job_workflow_ref` and use it to set the `builder.id`. We could just allow a nil value to be passed and then not set a `builder` if nil? With that in mind, the verifier may want to have some logic to make sure there is a `builder.id` set.
https://github.com/slsa-framework/slsa-github-generator/blob/main/slsa/provenance.go#L49-L52

Signatures done via OIDC are handled separately by cosign's github provider. So we should be fine w/ that if we just don't sign the provenance (now that I see this cosign could do with some OIDC token verification logic).
https://github.com/sigstore/cosign/blob/main/pkg/providers/github/github.go#L53-L65

**Comment by laurentsimon** [comment]
SGTM. Do you want to make the changes to the API or shall I do it?

Note: The verifier verifies the builder in the cert (https://github.com/slsa-framework/slsa-verifier/blob/f0ec07191c5b12affd326e49bfb1c94d0df3e2a2/main.go#L77), but not yet in the provenance itself. We have https://github.com/slsa-framework/slsa-verifier/issues/3 tracking it

**Pull request merged**
