### PR TITLE
✨ Change project location before merge into slsa-github-generator

### PR DESCRIPTION
**Pull request by laurentsimon**
This PR simply changes the location of the project to verify everything works before merging the code into the slsa-github-generator repo (see https://github.com/slsa-framework/slsa-github-generator/issues/36).

Note: Ignore the go.mod changes, https://github.com/slsa-framework/slsa-github-generator-go/pull/124 needs to be merged first

### CODE REVIEW

**Review by ianlewis — APPROVED** [review]
We may want to rearrange where the files are after we merge but I think these paths are ok, at least for now.

**Comment by laurentsimon** [comment]
> We may want to rearrange where the files are after we merge but I think these paths are ok, at least for now.

sg. How would you like me to tweak the paths?

**Comment by ianlewis** [comment]
> sg. How would you like me to tweak the paths? I could do it in the merge PR

I'm not sure yet. We could move builders under cmd/ or I could move the provenance only one under builders/? I just want to be consistent.

**Comment by ianlewis** [comment]
For now though just create a merge PR into slsa-github-generator with the paths you have currently and we can figure out how to clean it up a bit after that.

**Pull request merged**
